package com.theonlytails.craftingrecipes

/**
 * An enum class for all vanilla recipe groups.
 *
 * @see group
 * @author TheOnlyTails
 */
@Suppress("unused")
@CraftingRecipes
enum class RecipeGroup {
	BED,
	DYED_BED,
	DYED_CANDLE,

	BLACK_DYE,
	BLUE_DYE,
	BROWN_DYE,
	RED_DYE,
	WHITE_DYE,
	YELLOW_DYE,
	LIGHT_BLUE_DYE,
	LIGHT_GRAY_DYE,
	MAGENTA_DYE,
	ORANGE_DYE,
	PINK_DYE,

	STICKS,
	PLANKS,
	WOODEN_SLAB,
	WOODEN_STAIRS,
	WOODEN_DOOR,
	WOODEN_TRAPDOOR,
	WOODEN_FENCE,
	WOODEN_FENCE_GATE,
	WOODEN_SIGN,
	WOODEN_PRESSURE_PLATE,
	WOODEN_BUTTON,
	BOAT,
	BARK,

	BANNER,

	STAINED_GLASS,
	STAINED_GLASS_PANE,
	CONCRETE_POWDER,
	STAINED_TERRACOTTA,

	BONEMEAL,

	WOOL,
	CARPET,

	COAL,
	COPPER_INGOT,
	LAPIS_LAZULI,
	REDSTONE,
	GOLD_INGOT,
	IRON_INGOT,
	DIAMOND,

	POINTED_DRIPSTONE,

	MOSSY_COBBLESTONE,
	MOSSY_STONE_BRICKS,

	RABBIT_STEW,

	WAXED_COPPER_BLOCK,
	WAXED_WEATHERED_COPPER,
	WAXED_EXPOSED_COPPER,
	WAXED_OXIDIZED_COPPER,

	WAXED_COPPER_SLAB,
	WAXED_WEATHERED_COPPER_SLAB,
	WAXED_EXPOSED_COPPER_SLAB,
	WAXED_OXIDIZED_COPPER_SLAB,

	WAXED_COPPER_STAIRS,
	WAXED_WEATHERED_COPPER_STAIRS,
	WAXED_EXPOSED_COPPER_STAIRS,
	WAXED_OXIDIZED_COPPER_STAIRS,

	WAXED_CUT_COPPER,
	WAXED_WEATHERED_CUT_COPPER,
	WAXED_EXPOSED_CUT_COPPER,
	WAXED_OXIDIZED_CUT_COPPER,

	WAXED_CUT_COPPER_SLAB,
	WAXED_WEATHERED_CUT_COPPER_SLAB,
	WAXED_EXPOSED_CUT_COPPER_SLAB,
	WAXED_OXIDIZED_CUT_COPPER_SLAB,

	WAXED_CUT_COPPER_STAIRS,
	WAXED_WEATHERED_CUT_COPPER_STAIRS,
	WAXED_EXPOSED_CUT_COPPER_STAIRS,
	WAXED_OXIDIZED_CUT_COPPER_STAIRS,
}